In [16]:
import numpy as np
import pandas as pd

In [17]:
data = np.loadtxt('DATA.txt')
df = pd.DataFrame(data, columns=['GENDER', 'AGE', 'RF', 'SBP', 'HR1', 'ST', 'HR2', 'CRT', 'KIL', 'EVENT'])

display(df)

     GENDER   AGE   RF    SBP         HR1   ST    HR2  CRT  KIL  EVENT
0       1.0  33.0  0.0  132.0   91.579173  1.0   90.0  0.8  1.0    0.0
1       1.0  69.0  0.0  147.0   52.785861  0.0   52.0  1.4  1.0    0.0
2       1.0  63.0  0.0  142.0   40.692798  1.0   44.0  1.1  3.0    1.0
3       0.0  79.0  0.0  147.0  106.420820  1.0  110.0  0.9  1.0    1.0
4       0.0  61.0  0.0  107.0   82.148302  0.0   80.0  1.1  1.0    0.0
..      ...   ...  ...    ...         ...  ...    ...  ...  ...    ...
452     1.0  69.0  0.0   95.0   99.801711  0.0  103.0  1.6  3.0    1.0
453     1.0  51.0  1.0  140.0   87.339759  1.0   90.0  1.0  3.0    1.0
454     0.0  57.0  0.0  120.0  113.138910  0.0  117.0  1.0  3.0    1.0
455     1.0  87.0  0.0  149.0   50.035793  1.0   53.0  1.4  1.0    1.0
456     1.0  72.0  0.0  173.0   68.337300  1.0   65.0  1.2  1.0    0.0

[457 rows x 10 columns]

In [ ]:
df.history()

In [18]:
ev1 = df.loc[df['EVENT'] == 1.0]
ev0 = df.loc[df['EVENT'] == 0.0]

st1_ev1 = ev1.loc[ev1['ST'] == 1.0]
st1_ev0 = ev0.loc[ev0['ST'] == 1.0]

st0_ev1 = ev1.loc[ev1['ST'] == 0.0]
st0_ev0 = ev0.loc[ev0['ST'] == 0.0]

In [19]:
p_st1_ev1 = len(st1_ev1) / len(ev1)
p_st1_ev0 = len(st1_ev0) / len(ev0)

p_st0_ev1 = len(st0_ev1) / len(ev1)
p_st0_ev0 = len(st0_ev0) / len(ev0)

In [20]:
kil4_ev1 = ev1.loc[ev1['KIL'] == 4.0]
kil4_ev0 = ev0.loc[ev0['KIL'] == 4.0]

kil3_ev1 = ev1.loc[ev1['KIL'] == 3.0]
kil3_ev0 = ev0.loc[ev0['KIL'] == 3.0]

kil2_ev1 = ev1.loc[ev1['KIL'] == 2.0]
kil2_ev0 = ev0.loc[ev0['KIL'] == 2.0]

kil1_ev1 = ev1.loc[ev1['KIL'] == 1.0]
kil1_ev0 = ev0.loc[ev0['KIL'] == 1.0]

kil0_ev1 = ev1.loc[ev1['KIL'] == 0.0]
kil0_ev0 = ev0.loc[ev0['KIL'] == 0.0]

In [21]:
p_kil4_ev1 = len(kil4_ev1) / len(ev1)
p_kil4_ev0 = len(kil4_ev0) / len(ev0)

p_kil3_ev1 = len(kil3_ev1) / len(ev1)
p_kil3_ev0 = len(kil3_ev0) / len(ev0)

p_kil2_ev1 = len(kil2_ev1) / len(ev1)
p_kil2_ev0 = len(kil2_ev0) / len(ev0)

p_kil1_ev1 = len(kil1_ev1) / len(ev1)
p_kil1_ev0 = len(kil1_ev0) / len(ev0)

p_kil0_ev1 = len(kil0_ev1) / len(ev1)
p_kil0_ev0 = len(kil0_ev0) / len(ev0)

In [22]:
rf1_ev1 = ev1.loc[ev1['RF'] == 1.0]
rf1_ev0 = ev0.loc[ev0['RF'] == 1.0]

rf0_ev1 = ev1.loc[ev1['RF'] == 0.0]
rf0_ev0 = ev0.loc[ev0['RF'] == 0.0]

In [23]:
p_rf1_ev1 = len(rf1_ev1) / len(ev1)
p_rf1_ev0 = len(rf1_ev0) / len(ev0)

p_rf0_ev1 = len(rf0_ev1) / len(ev1)
p_rf0_ev0 = len(rf0_ev0) / len(ev0)